name: Update Azure Synapse Serverless SQL Pool

# Sample of how to deploy to an Azure Synapse Serverless SQL Pool using GitHub Actions
# You can use a self-hosted runner installed locally for this to work
# You can also use a GitHub-hosted runner

# For this pipeline you also need to setup the below encrypted secrets (https://bit.ly/3nd0Jj8)
  # sqlinstance - Your Serverless SQL Pool endpoint 
    #(the one that ends with -ondemand)
  # database - The database in the SQL Pool you want the update deployed to
    # Note it has to exist BEFORE this the scripts are run
  # UserName - User name to connect to the Serverless SQL Pool endpoint
    # try and keep this secret
  # Pw - Password of above user, definitely keep this one secret

#Sets the trigger to update when update is pushed to main branch
on:
  push:
    branches: 
      - main

jobs:

  # Job to install the scripts
  ServerlessPool1:
    # Easier to use Github-hosted runner if updating in GitHub
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      # Note that I am using latest version of action
      - uses: actions/checkout@v2.4.0 

      # install dbops PowerShell module
      - name: Install dbops module
        run: 'Install-Module -Name dbops -Force -PassThru'
        
      # Run migration-based scripts
      - name: Run migration-based scripts
        run: |
          $SecurePw=ConvertTo-SecureString ${{ secrets.Pw }} –asplaintext –force
          Install-DBOScript -ScriptPath scripts -sqlinstance ${{ secrets.sqlinstance }} -Database ${{ secrets.database }} -UserName ${{ secrets.UserName }} -Password $SecurePw -SchemaVersionTable $null
